# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
#include: package:pedantic/analysis_options.yaml
include: package:effective_dart/analysis_options.1.3.0.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    always_specify_types: true
    omit_local_variable_types: false
    lines_longer_than_80_chars: false

analyzer:
#   exclude:
#     - path/to/excluded/files/**
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
